
spring:
  application:
    name: ms-cursos

  datasource:
    url: jdbc:postgresql://localhost:5432/ms-cursos
    username: 'camilomeneses'
    password: '@cam123lo_pass'
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
server:
  port: 8002
logging:
  level:
    org.hibernate.sql: debug
