
spring:
  application:
    name: ${APP_NAME:ms-cursos}

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres15:5432}/${DB_DATABASE:ms-cursos}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
server:
  port: ${PORT:8002}

logging:
  level:
    org:
      hibernate:
        SQL: debug

## Variables de ambiente app
ms:
  usuarios:
    url: ${USUARIOS_URL:ms-usuarios:8001}